### PR TITLE
Add launch lesson link feature

### PR DESCRIPTION
**Pull request by richwill28**
## Changelog

* Add `LinkUtil` class to process link-related operations
* Implement URL launching for `Lesson`

### CODE REVIEW

**Comment by richwill28** [comment]
@ptejasv Could you help me test if this is working on **Mac**?

@Roycius Could you help me test if this is working on **Windows**?

**Comment by rebchua39** [comment]
> @ptejasv Could you help me test if this is working on **Mac**?
> 
> @Roycius @rebchua39 Could you help me test if this is working on **Windows**?
> 
> If some of you also test it on **Linux** please inform me as well.

Yup, it works on Windows.

**Review by ptejasv — APPROVED** [review]
LGTM

**Comment by richwill28** [comment]
As of 9ae7a48, this feature is working on..

* Windows (according to @rebchua39 and @Roycius )
* Mac (according to @ptejasv)
* Linux (according to @richwill28)
* WSL (according to @richwill28)

**Pull request merged**
